const n = 4;

for (let i = 1; i <= n; i++) {
  let row = "";
  // declare an empty string for the rows to be generated
  for (let j = 1; j <= i; j++){
    // inner loop adds # characters to the current row generated by outer loop
    row += "#";
    // each new iteration of the inner loop creates a new row with one more # character
  }
  console.log(row)
}

//Output logic:
// #
// ##
// ###
// ####
